title = "CloudEvents"
baseURL = "/"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "A specification for describing event data in a common way"
font_awesome_version = "5.11.2"

[params.logos]
navbar = "cloudevents-icon-color.png"
hero = "cloudevents-icon-color.png"
footer = "cloudevents-icon-color.png"

[params.why]
heading = "Events are everywhere, yet event publishers tend to describe events differently."

[[params.why.tiles]]
heading = "Consistency"
text = "The lack of a common way of describing events means developers have to write new event handling logic for each event source."
icon = "fas fa-code"

[[params.why.tiles]]
heading = "Accessibility"
text = "No common event format means no common libraries, tooling, and infrastructure for delivering event data across environments. CloudEvents provides SDKs for [Go](https://github.com/cloudevents/sdk-go), [JavaScript](https://github.com/cloudevents/sdk-javascript), [Java](https://github.com/cloudevents/sdk-java), [C#](https://github.com/cloudevents/sdk-csharp), [Ruby](https://github.com/cloudevents/sdk-ruby), and [Python](https://github.com/cloudevents/sdk-python) that can be used to build event routers, tracing systems, and other tools."
icon = "fas fa-universal-access"

[[params.why.tiles]]
heading = "Portability"
text = "The portability and productivity we can achieve from event data is hindered overall."
icon = "far fa-gem"

[params.what]
text = """
CloudEvents is a [specification](https://github.com/cloudevents/spec/blob/master/spec.md) for describing event data in a common way. CloudEvents seeks to dramatically simplify event declaration and delivery across services, platforms, and beyond!

CloudEvents is a new effort and it's still under active development. However, its working group has received a surprising amount of industry interest, ranging from major cloud providers to popular SaaS companies. The specification is now under the [Cloud Native Computing Foundation](https://cncf.io).
"""

[params.contribute]
text = """
CloudEvents is organized via the CNCF's [Serverless Working Group](https://github.com/cncf/wg-serverless) and everyone is encouraged to join us. If you're interested in contributing, please collaborate with us in the [CloudEvents Github org](https://github.com/cloudevents), join our weekly call every Thursday at [9AM PT](http://www.thetimezoneconverter.com/?t=9:00 am&tz=San Francisco) via [Zoom](https://zoom.us/my/cncfserverlesswg), check the [meeting notes](https://docs.google.com/document/d/1xwcsWQmMiRN24a7o7oy9MstzMroAup31oOkM5Dru1jQ), and review our [Governance](https://github.com/cloudevents/spec/blob/master/community/GOVERNANCE.md) model to familiarize yourself with our process.
"""

[params.release]
text = """
On October 24, 2019 the CloudEvents project had two significant achievements. First, the CNCF's [Technical Oversight Committee](https://github.com/cncf/toc) approved the project as an "incubator" project (thus graduating it from the CNCF "sandbox"). Second, the CloudEvents specification released version 1.0!

This is the first major release of the specification and represents two years' worth of hard work by a truly great team of people from across the entire serverless community. We've had just about every major cloud provider participate, several "end user" companies as well as many individual participants all working diligently on producing a specification that will hopefully continue to see increased adoption now that this milestone has been reached.

Aside from the [core CloudEvents specification](https://github.com/cloudevents/spec/blob/v1.0/spec.md), there's also the [Primer](https://github.com/cloudevents/spec/blob/v1.0/primer.md) and protocol and format specifications, all of which can be found in the [GitHub repo](https://github.com/cloudevents/spec). Additionally, there are six different [SDKs](https://github.com/cloudevents/spec#sdks)—[Go](https://github.com/cloudevents/sdk-go), [JavaScript](https://github.com/cloudevents/sdk-javascript), [Java](https://github.com/cloudevents/sdk-java), [C#](https://github.com/cloudevents/sdk-csharp), [Ruby](https://github.com/cloudevents/sdk-ruby), and [Python](https://github.com/cloudevents/sdk-python)—to help people produce and consume CloudEvents.

The CNCF Serverless Working Group will be deciding what to focus on next (e.g. additional CloudEvents related activities, or perhaps address some other interoperability pain-point the community is experiencing). So, if you're interested please join the regular [weekly calls](https://github.com/cloudevents/spec#meeting-time). Additionally, there is the work being done on the [workflow specification](https://github.com/cncf/wg-serverless/tree/master/workflow/spec).

Thanks and congratulations to everyone who has participated in the CloudEvents project! 
"""

[[params.fonts]]
name = "Montserrat"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[menus.main]]
name = "Specification"
url = "https://github.com/cloudevents/spec"
weight = 1

[[menus.main]]
name = "Primer"
url = "https://github.com/cloudevents/spec/blob/master/primer.md"
weight = 2

[[menus.main]]
identifier = "project"
name = "Project"
weight = 3

[[menus.main]]
name = "Code of conduct"
url = "https://github.com/cncf/foundation/blob/master/code-of-conduct.md"
parent = "project"
weight = 1

[[menus.main]]
name = "Governance"
url = "https://github.com/cloudevents/spec/blob/master/GOVERNANCE.md"
parent = "project"
weight = 2

[[menus.main]]
name = "Contributors"
url = "https://github.com/cloudevents/spec/blob/master/community/contributors.md"
parent = "project"
weight = 3

[[params.sdks]]
name = "Go"
tag = "go"

[[params.sdks]]
name = "JavaScript"
tag = "javascript"

[[params.sdks]]
name = "Java"
tag = "java"

[[params.sdks]]
name = "C#"
tag = "csharp"

[[params.sdks]]
name = "Ruby"
tag = "ruby"

[[params.sdks]]
name = "Python"
tag = "python"

[[params.sdks]]
name = "Rust"
tag = "rust"

[[params.social]]
tag = "github"
name = "GitHub"
url = "https://github.com/cloudevents"
color = "black"

[[params.social]]
tag = "twitter"
name = "Twitter"
url = "https://twitter.com/CloudEventsIO"
color = "twitter-blue"
