# Site settings
baseurl = "https://cloudevents.io/"
languageCode = "en-us"
title = "CloudEvents"
theme = "hugo-stellar-theme"
canonifyurls = true
googleAnalytics = ""

[params]
groupsiourl = "https://lists.cncf.io/g/cncf-cloudevents/signup?u=2254653446843417778"
groupsioid = "2254653446843417778"
github = "https://github.com/cloudevents/spec"

  [params.header]
    title = ""
    description = "A specification for describing event data in a common way"
    image = "img/cloudevents.png"

  [[params.navigation]]
    name = "Why?"
    href = "#why"

  [[params.navigation]]
    name = "What?"
    href = "#what"

  [[params.navigation]]
    name = "Contribute"
    href = "#contribute"

  [[params.navigation]]
    name = "v0.3 Announcement"
    href = "#v03"

  # [params.intro]
  #   title = "Why?"
  #   description = "Sed lorem ipsum dolor sit amet nullam consequat feugiat consequat magna adipiscing magna etiam amet veroeros. Lorem ipsum dolor tempus sit cursus. Tempus nisl et nullam lorem ipsum dolor sit amet aliquam."
  #   image = "images/pic01.jpg"
  #   [[params.intro.action]]
  #     buttontext = "Learn More"
  #     href = "generic.html"


  [[params.section]]
    id = "why"
    title = "Why?"
    description = "Events are everywhere.  However, event publishers tend to describe events differently."
    
    # the picture is storead at static/images/
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Consistency"
        description = "The lack of a common way of describing events means developers must constantly re-learn how to receive events."
        icon = "fa-code"

      [[params.section.feature]]
        title = "Accessibility"
        description = "This also limits the potential for libraries, tooling and infrastructure to aide the delivery of event data across environments, like SDKs, event routers or tracing systems."
        icon = "fa-copy"

      [[params.section.feature]]
        title = "Portability"
        description = "The portability and productivity we can achieve from event data is hindered overall."
        icon = "fa-diamond"
    [params.section.footer]
      enable = false
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [[params.section]]
    id = "what"
    title = "What?"
    description = "Enter CloudEvents, a specification for describing event data in a common way. CloudEvents seeks to ease event declaration and delivery across services, platforms and beyond!\n\nCloudEvents is a new effort and it's still under active development.  However, its working group has received a surprising amount of industry interest, ranging from major cloud providers to popular SaaS companies.  Our end goal is to offer this specification to the [Cloud Native Computing Foundation](https://serverless.us11.list-manage.com/pages/track/click?u=b4fad36768cab222f88338995&id=59a5aec830)."

    [params.section.statistics]
      enable = false
      [[params.section.statistic]]
        icon = "fa-code-fork"
        value = "5,120"
        text = "Etiam"
      [[params.section.statistic]]
        icon = "fa-folder-open-o"
        value = "8,192"
        text = "Magna"
      [[params.section.statistic]]
        icon = "fa-signal"
        value = "2,048"
        text = "Tempus"
      [[params.section.statistic]]
        icon = "fa-laptop"
        value = "4,096"
        text = "Aliquam"
      [[params.section.statistic]]
        icon = "fa-diamond"
        value = "1,024"
        text = "Nullam"

    [params.section.content]
      enable = false
      text = "Nam elementum nisl et mi a commodo porttitor. Morbi sit amet nisl eu arcu faucibus hendrerit vel a risus. Nam a orci mi, elementum ac arcu sit amet, fermentum pellentesque et purus. Integer maximus varius lorem, sed convallis diam accumsan sed. Etiam porttitor placerat sapien, sed eleifend a enim pulvinar faucibus semper quis ut arcu. Ut non nisl a mollis est efficitur vestibulum. Integer eget purus nec nulla mattis et accumsan ut magna libero. Morbi auctor iaculis porttitor. Sed ut magna ac risus et hendrerit scelerisque. Praesent eleifend lacus in lectus aliquam porta. Cras eu ornare dui curabitur lacinia."

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Cloud Native Computing Foundation"
        buttonUrl = "https://serverless.us11.list-manage.com/pages/track/click?u=b4fad36768cab222f88338995&id=59a5aec830"


  [[params.section]]
    id = "contribute"
    title = "Contribute!"
    description = "This effort is organized via the CNCF's [Serverless Working Group](https://github.com/cncf/wg-serverless) and everyone is encouraged to join us.  If you're interested in contributing, please collaborate with us in the [CloudEvents Github Org](https://github.com/cloudevents), join our weekly call every Thursday at 9AM PT via [Zoom](https://zoom.us/my/cncfserverlesswg), and review our [Governance](https://github.com/cloudevents/spec/blob/master/GOVERNANCE.md) model to familiarize yourself with our process."
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Serverless Working Group"
        buttonUrl = "https://github.com/cncf/wg-serverless"
      [[params.section.footer.action]]
        buttontext = "CloudEvents Github Org"
        buttonUrl = "https://github.com/cloudevents"
      [[params.section.footer.action]]
        buttontext = "Governance"
        buttonUrl = "https://github.com/cloudevents/spec/blob/master/GOVERNANCE.md"

  [[params.section]]
    id = "v03"
    title = "v0.3 Announcement!"
    description = """# CloudEvents 0.3 Release

<span style="text-align:left">
On June 13 the CloudEvents project approved version 0.3 of the specification and accompanying documents. It's been about 6 months since the last release and there have been a lot of really good changes that have been made since then. However, before we get into the list of changes, let's first discuss what this release really means. While the version number appears very small, don't let that fool you. Our [roadmap](https://github.com/cloudevents/spec/blob/master/roadmap.md) only goes up to v0.5 and if you look at the list of work items for 0.4 and 0.5, most are related to clarifications or working on secondary documents, like additional protocol bindings. The point is that the group considers the 'core' part of the spec to be nearing completion - and that's huge!

While we expect stability as we reach v1.0, we don't know what will pop up during our testing and verification phase that we're planning on doing prior to v1.0. But it means that we consider the bigger design decisions to be behind us. We have agreed on the scope and goals of the specification, and we're just putting the final touches on things. As proof, as of this writing, we don't have any open PRs targeted for v1.0 and only 9 open issues.

The current plan is to try to resolve these remaining issues within weeks and then determine how long we'll need for a final review and verification phase. We already have CloudEvents being used by several key Cloud players and open-source projects, so that already gives us a good feeling about its readiness.  Net: watch this space!

Let's discuss some of the bigger changes in the specifications since v0.2:<br>
- An SDK design doc was been provided to help guide SDK authors and to promote consistency (when appropriate) between the various language SDKs.<br>
- We enabled support for batching of CloudEvents. It mainly becomes a transport issue, but we do describe how to do it for HTTP.<br>
- The "contenttype" attribute has been renamed to "datacontenttype". While this might seem trivial, the potential confusion of this attribute with the Content-Type HTTP header was a sore point for many people.<br>
- In the area of security, we added some guidance around how to manage sensitive data.<br>
- In order to help promote interop, we mandated that CloudEvent components needs to support messages at of least 64k in size.<br>
- A "subject" attribute was added. While "source" indicates where the event came from, "subject" indicates which resource the event is about.<br>
- Added some processing rules around how to serialize the data types, in particular unknown extensions. In the end, they're just strings if the transport doesn't support a type system.<br>
- Two new extensions were defined: "dataref" which can be used for a claim-check pattern of retrieval of large data, and "paritionkey" which helps consumers place the incoming event into the correct grouping mechanism for more efficient processing.<br>
- A section for pointing to "proprietary" protocols that define a CloudEvents mapping was added. This allows for transports that are mainly focused on one particular implementation to still be included within the project. The first one to be added was a reference to the RocketMQ CloudEvents mapping.<br>
- Clarified which properties are used for uniqueness checking, to enable de-dupe logic if necessary

Finally, the [SDK](https://github.com/cloudevents/spec#sdks) work is continuing nicely, so if you're interested in using CloudEvent those might be helpful in your coding efforts. And if you're interested in learning more about CloudEvents you should go to the [github repo](https://github.com/cloudevents/spec) and start by reading the [Primer](https://github.com/cloudevents/spec/blob/v0.3/primer.md). It provides a good overview of the project goals and design decisions. Then, of course, the [spec](https://github.com/cloudevents/spec/blob/v0.3/spec.md) itself is where you'll get all of the details you'll need about CloudEvents.

TOC sponsors of the project include Ken Owens and Brian Grant.

The CNCF Sandbox is a home for early stage projects, for further clarification around project maturity levels in CNCF, please visit our outlined [Graduation Criteria](https://www.cncf.io/projects/graduation-criteria/).
</span>
"""

  [params.footer]
    enable = true
    title = "CloudEvents"
    description = "A specification for describing event data in a common way."

    [[params.footer.action]]
      href = "https://github.com/cloudevents/spec"
      buttontext = "Learn More"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Github"
        icon = "fa-github"
        link = "https://github.com/cloudevents/spec"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "Â© CloudEvents.io 2018"
